default_platform(:android)

platform :android do

  desc "Analiza el código con SonarQube"

    lane :scan_code do |options|

      target_module = options[:module]

      sonar_module_name = target_module.delete_prefix(":")

      UI.message("🎯 Enfocando análisis en: #{target_module}")

      gradle(task: "clean #{target_module}:assembleDebug")

      if ENV['SONAR_TOKEN']
        gradle(
          task: "sonar",
          flags: "--info " +
                 "--init-script /workspace/sonar-injection.gradle.kts " +
                 "-Dsonar.host.url=#{ENV['SONAR_HOST_URL']} " +
                 "-Dsonar.token=#{ENV['SONAR_TOKEN']} " +
                 "-Dsonar.projectKey=#{ENV['SONAR_PROJECT_KEY']}:#{sonar_module_name} " +
                 "-Dsonar.projectName='#{sonar_module_name}' " +
                 "-Dsonar.includedModules=#{sonar_module_name}"
        )
      end
    end

  desc "Publica el artefacto en Nexus"
    lane :publish_nexus do |options|

        target_module = options[:module]

        UI.message("🚀 Publicando SOLO el módulo: #{target_module}")

        sh("sed -i 's/\r$//' ./gradlew")

        gradle(task: "#{target_module}:publishReleasePublicationToNexusOnPremiseRepository")
    end